# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEwIJx0HUuL2pHPRyhLQv46vomSEF-Vx
"""

pip install PyTDC rdkit pandas==2.2.0 numpy==1.26.4 matplotlib seaborn

import pandas as pd
from tdc.single_pred import ADME, Tox
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem
import matplotlib.pyplot as plt
import seaborn as sns
from tdc.utils import retrieve_label_name_list

# 1. Download Real Datasets from TDC
print("Downloading datasets...")
# Reference: Solubility data (Standard Drug-like molecules)
data_ref = ADME(name = 'solubility_aqsoldb').get_data().head(500)
# Test: Toxicity data (Often more diverse/complex structures)

# Retrieve available label names for 'tox21'
tox21_labels = retrieve_label_name_list('tox21')
# For simplicity, we'll pick the first label. In a real scenario, you might choose based on your specific task.
selected_tox21_label = tox21_labels[0]
print(f"Selected Tox21 label: {selected_tox21_label}")

data_test = Tox(name = 'Tox21', label_name = selected_tox21_label).get_data().head(100)

def get_fps(smiles_list):
    fps = []
    for s in smiles_list:
        m = Chem.MolFromSmiles(s)
        if m:
            fps.append(AllChem.GetMorganFingerprintAsBitVect(m, 2, nBits=2048))
    return fps

# 2. Generate Fingerprints
print("Generating Fingerprints...")
ref_fps = get_fps(data_ref['Drug'].tolist())
test_fps = get_fps(data_test['Drug'].tolist())

# 3. Calculate "Nearest Neighbor" Similarity
# For each test molecule, find its most similar match in the reference set
print("Calculating OOD Scores...")
max_sims = []
for t_fp in test_fps:
    sims = DataStructs.BulkTanimotoSimilarity(t_fp, ref_fps)
    max_sims.append(max(sims))

# 4. Visualization & Analysis
plt.figure(figsize=(10, 6))
sns.kdeplot(max_sims, fill=True, color="royalblue", bw_adjust=0.5)
plt.axvline(x=0.5, color='red', linestyle='--', label='OOD Threshold (0.5)')
plt.title("Applicability Domain Analysis: Tox21 vs. AqSolDB", fontsize=14)
plt.xlabel("Max Tanimoto Similarity", fontsize=12)
plt.ylabel("Density", fontsize=12)
plt.legend()
plt.grid(alpha=0.3)
plt.savefig('ood_plot.png')
plt.show()

# 5. Quick Stats for your GitHub README
ood_count = sum(1 for x in max_sims if x < 0.5)
print(f"Project Summary:")
print(f"- Total test molecules analyzed: {len(max_sims)}")
print(f"- Molecules flagged as OOD (<0.5 similarity): {ood_count}")
print(f"- OOD Percentage: {(ood_count/len(max_sims))*100:.1f}%")